# Generated by Django 4.0.3 on 2022-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
