# Generated by Django 4.0.3 on 2022-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_task_priority_task_status_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
